// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhLzHE-xwOn9SdKue2fAiX1Lc3m1hpkA',
    appId: '1:593151530958:web:90dfd6843e44b8fb873d9f',
    messagingSenderId: '593151530958',
    projectId: 'grant-45f5c',
    authDomain: 'grant-45f5c.firebaseapp.com',
    storageBucket: 'grant-45f5c.firebasestorage.app',
    measurementId: 'G-MSL0WX21QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwDFhDPXRF1_1cReBu02kGwB5WAm68QrI',
    appId: '1:593151530958:android:30bdd2d4cde8a2e8873d9f',
    messagingSenderId: '593151530958',
    projectId: 'grant-45f5c',
    storageBucket: 'grant-45f5c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGhLzHE-xwOn9SdKue2fAiX1Lc3m1hpkA',
    appId: '1:593151530958:web:90dfd6843e44b8fb873d9f',
    messagingSenderId: '593151530958',
    projectId: 'grant-45f5c',
    authDomain: 'grant-45f5c.firebaseapp.com',
    storageBucket: 'grant-45f5c.firebasestorage.app',
    measurementId: 'G-MSL0WX21QS',
  );
}
